language: scala
sudo: false
scala:
  - "2.11.8"
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
sudo: required
services:
  - rabbitmq
  - cassandra
script:
  - sbt +test
